Repository Pritanshu69/Amazon_homepage-, pull requests merged in 2024-01, with the labels that each got.

#50 Made shop section responsive as well as added styles
  index.html
  style.css
Labels: enhancement, hard, apertre, points: 15

#57 footerhtml
  index.html
Labels: enhancement, hard, apertre, points: 15

#61 Make Amazon.in Message responsive for all device
  style.css
Labels: easy, points: 5

#70 Feature:- icon
  amazon.png
  index.html
Labels: easy, apertre, points: 5

#67 Update index.html
  index.html
Labels: easy, apertre, points: 5

#76 Added more boxes in shopping section and also added working to (back to top) & (click here to go to amazon.in) buttons.
  box10_image.jpg
  box11_image.jpg
  box12_image.jpg
  box9_image.jpg
  index.html
  style.css
Labels: medium, apertre, points: 10

#75 Test
  amazon.png
  box10_image.jpg
  box11_image.jpg
  box12_image.jpg
  box9_image.jpg
  index.html
  style.css
Labels: easy, apertre

#78 Issue #11 solved
  crouselamazon2.jpg
  index.html
  style.css
Labels: enhancement, medium, apertre, points: 10

#79 Fixed responsiveness of footbar
  crouselamazon2.jpg
  index.html
  style.css
Labels: enhancement, medium, apertre, points: 10

#80 Ustav's Test update
  style.css
Labels: medium, apertre

#86 Added the image slider
  banner-1.png
  banner-2.png
  banner-3.png
  banner-4.png
  index.html
  script.js
  style.css
Labels: medium, apertre, points: 10

#91 Fixed bugs in image display of box
  index.html
Labels: bug, medium, points: 10

#100 Added hamburger menu
  cross-button.png
  index.html
  script.js
  sign-in.png
  style.css
Labels: medium, apertre, points: 10

#102 navbar
  SWM_400x39_V1._CB585205801_.jpg
  index.html
  style.css
Labels: enhancement, easy, apertre

#105 Footer update
  SWM_400x39_V1._CB585205801_.jpg
  cross-button.png
  index.html
  script.js
  sign-in.png
  style.css
Labels: easy, apertre

#108 added links to the moving images
  index.html
Labels: medium, apertre

#112 footlink index.html
  index.html
Labels: easy, apertre, points: 5

#118 Added hamburger menu links
  index.html
  style.css
Labels: medium, apertre

#119 Signin signup
  .vscode/settings.json
  index.html
  sign_in.css
  sign_in.html
  signin_signup.js
  style.css
Labels: hard, apertre

#120 #96 issue solved
  index.html
  style.css
Labels: easy, apertre

#122 added links in the footer of different country's amazon page and aligned panel options to the left (#116)
  index.html
  style.css
Labels: easy, apertre

#140 added more sections
  asset/1.png
  asset/10.png
  asset/11.png
  asset/12.png
  asset/13.png
  asset/14.png
  asset/15.png
  asset/16.png
  asset/17.png
  asset/18.png
  asset/19.png
  asset/2.png
  asset/20.png
  asset/21.png
  asset/22.png
  asset/23.png
  asset/24.png
  asset/25.png
  asset/26.png
  asset/27.png
  asset/28.jpg
  asset/28.png
  asset/29.png
  asset/3.png
  asset/30.png
  asset/31.png
  asset/32.png
  asset/33.png
  asset/34.png
  asset/35.png
  asset/36.png
  asset/37.png
  asset/38.png
  asset/39.png
  asset/4.png
  asset/5.png
  asset/6.png
  asset/7.png
  asset/8.png
  asset/9.png
  index.html
  style.css
Labels: medium, apertre

#142 Csshead
  asset/1.png
  asset/10.png
  asset/11.png
  asset/12.png
  asset/13.png
  asset/14.png
  asset/15.png
  asset/16.png
  asset/17.png
  asset/18.png
  asset/19.png
  asset/2.png
  asset/20.png
  asset/21.png
  asset/22.png
  asset/23.png
  asset/24.png
  asset/25.png
  asset/26.png
  asset/27.png
  asset/28.jpg
  asset/28.png
  asset/29.png
  asset/3.png
  asset/30.png
  asset/31.png
  asset/32.png
  asset/33.png
  asset/34.png
  asset/35.png
  asset/36.png
  asset/37.png
  asset/38.png
  asset/39.png
  asset/4.png
  asset/5.png
  asset/6.png
  asset/7.png
  asset/8.png
  asset/9.png
  index.html
  style.css
Labels: medium, apertre

#146 made a login page for amazon website (#137)
  asset/amazon-logo.png
  login.css
  login.html
Labels: medium, apertre

#152 solved the issue #134
  aos/aos.css
  aos/aos.js
  index.html
  script.js
Labels: medium, apertre

#151 Update README.md
  README.md
Labels: documentation, easy, apertre

#167 ui/ux improved
  index.html
  style.css
Labels: enhancement, hard, apertre, points: 15

#175 Responsive
  index.html
  style.css
Labels: medium, apertre, points: 10

#184 Add Cart page in the website
  cart.css
  cart.html
  index.html
  javascript.js
  todayDeal.js
Labels: medium, apertre
